### ISSUE TITLE
Nikola

### ISSUE THREAD

**Issue by lazarmax1** [usern4mehere9/nivo_bazena#1]
kako si

**Comment by lazarmax1** [comment]
@usern4mehere9  nikolaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by usern4mehere9** [comment]
> kako si

Dobro ti?

**Comment by lazarmax1** [comment]
> 
> 
> > kako si
> 
> Dobro ti?

dobro
